/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const WorkLogTimeSpan = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
});
export const WorkLogCategory = IDL.Variant({
  'creative' : IDL.Null,
  'wellness' : IDL.Null,
  'physical' : IDL.Null,
  'knowledge' : IDL.Null,
});
export const NewWorkLog = IDL.Record({
  'time' : WorkLogTimeSpan,
  'description' : IDL.Text,
  'category' : WorkLogCategory,
});
export const DAOProposal = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'noVotes' : IDL.Nat,
  'title' : IDL.Text,
  'yesVotes' : IDL.Nat,
  'description' : IDL.Text,
  'proposer' : IDL.Principal,
  'budget' : IDL.Nat,
});
export const ValidationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const WorkLog = IDL.Record({
  'id' : IDL.Nat,
  'status' : ValidationStatus,
  'time' : WorkLogTimeSpan,
  'description' : IDL.Text,
  'category' : WorkLogCategory,
  'worker' : IDL.Principal,
  'validations' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VotingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkAirdrop' : IDL.Func([IDL.Vec(IDL.Principal), IDL.Nat], [], []),
  'createWorkLog' : IDL.Func([NewWorkLog], [IDL.Nat], []),
  'getAllDAOProposals' : IDL.Func([], [IDL.Vec(DAOProposal)], ['query']),
  'getAllWorkLogs' : IDL.Func([], [IDL.Vec(WorkLog)], ['query']),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCitizenIdByPrincipal' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVotingStatus' : IDL.Func([IDL.Nat], [VotingStatus], ['query']),
  'getWorkLogsByCategory' : IDL.Func(
      [WorkLogCategory],
      [IDL.Vec(WorkLog)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'onboardCitizen' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProposal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Time],
      [IDL.Nat],
      [],
    ),
  'transfer' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'validateWorkLog' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const WorkLogTimeSpan = IDL.Record({ 'startTime' : Time, 'endTime' : Time });
  const WorkLogCategory = IDL.Variant({
    'creative' : IDL.Null,
    'wellness' : IDL.Null,
    'physical' : IDL.Null,
    'knowledge' : IDL.Null,
  });
  const NewWorkLog = IDL.Record({
    'time' : WorkLogTimeSpan,
    'description' : IDL.Text,
    'category' : WorkLogCategory,
  });
  const DAOProposal = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'noVotes' : IDL.Nat,
    'title' : IDL.Text,
    'yesVotes' : IDL.Nat,
    'description' : IDL.Text,
    'proposer' : IDL.Principal,
    'budget' : IDL.Nat,
  });
  const ValidationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const WorkLog = IDL.Record({
    'id' : IDL.Nat,
    'status' : ValidationStatus,
    'time' : WorkLogTimeSpan,
    'description' : IDL.Text,
    'category' : WorkLogCategory,
    'worker' : IDL.Principal,
    'validations' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VotingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkAirdrop' : IDL.Func([IDL.Vec(IDL.Principal), IDL.Nat], [], []),
    'createWorkLog' : IDL.Func([NewWorkLog], [IDL.Nat], []),
    'getAllDAOProposals' : IDL.Func([], [IDL.Vec(DAOProposal)], ['query']),
    'getAllWorkLogs' : IDL.Func([], [IDL.Vec(WorkLog)], ['query']),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCitizenIdByPrincipal' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVotingStatus' : IDL.Func([IDL.Nat], [VotingStatus], ['query']),
    'getWorkLogsByCategory' : IDL.Func(
        [WorkLogCategory],
        [IDL.Vec(WorkLog)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'onboardCitizen' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProposal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Time],
        [IDL.Nat],
        [],
      ),
    'transfer' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'validateWorkLog' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };