/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DAOProposal {
  'id' : bigint,
  'startTime' : Time,
  'noVotes' : bigint,
  'title' : string,
  'yesVotes' : bigint,
  'description' : string,
  'proposer' : Principal,
  'budget' : bigint,
}
export interface NewWorkLog {
  'time' : WorkLogTimeSpan,
  'description' : string,
  'category' : WorkLogCategory,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ValidationStatus = { 'pending' : null } |
  { 'completed' : null };
export type VotingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface WorkLog {
  'id' : bigint,
  'status' : ValidationStatus,
  'time' : WorkLogTimeSpan,
  'description' : string,
  'category' : WorkLogCategory,
  'worker' : Principal,
  'validations' : bigint,
}
export type WorkLogCategory = { 'creative' : null } |
  { 'wellness' : null } |
  { 'physical' : null } |
  { 'knowledge' : null };
export interface WorkLogTimeSpan { 'startTime' : Time, 'endTime' : Time }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAirdrop' : ActorMethod<[Array<Principal>, bigint], undefined>,
  'createWorkLog' : ActorMethod<[NewWorkLog], bigint>,
  'getAllDAOProposals' : ActorMethod<[], Array<DAOProposal>>,
  'getAllWorkLogs' : ActorMethod<[], Array<WorkLog>>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCitizenIdByPrincipal' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVotingStatus' : ActorMethod<[bigint], VotingStatus>,
  'getWorkLogsByCategory' : ActorMethod<[WorkLogCategory], Array<WorkLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'onboardCitizen' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProposal' : ActorMethod<[string, string, bigint, Time], bigint>,
  'transfer' : ActorMethod<[Principal, bigint], undefined>,
  'validateWorkLog' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];