/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkLogTimeSpan {
    startTime: Time;
    endTime: Time;
}
export type Time = bigint;
export interface WorkLog {
    id: bigint;
    status: ValidationStatus;
    time: WorkLogTimeSpan;
    description: string;
    category: WorkLogCategory;
    worker: Principal;
    validations: bigint;
}
export interface DAOProposal {
    id: bigint;
    startTime: Time;
    noVotes: bigint;
    title: string;
    yesVotes: bigint;
    description: string;
    proposer: Principal;
    budget: bigint;
}
export interface NewWorkLog {
    time: WorkLogTimeSpan;
    description: string;
    category: WorkLogCategory;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum ValidationStatus {
    pending = "pending",
    completed = "completed"
}
export enum VotingStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum WorkLogCategory {
    creative = "creative",
    wellness = "wellness",
    physical = "physical",
    knowledge = "knowledge"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkAirdrop(recipients: Array<Principal>, amount: bigint): Promise<void>;
    createWorkLog(input: NewWorkLog): Promise<bigint>;
    getAllDAOProposals(): Promise<Array<DAOProposal>>;
    getAllWorkLogs(): Promise<Array<WorkLog>>;
    getBalance(principal: Principal): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCitizenIdByPrincipal(principal: Principal): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVotingStatus(arg0: bigint): Promise<VotingStatus>;
    getWorkLogsByCategory(category: WorkLogCategory): Promise<Array<WorkLog>>;
    isCallerAdmin(): Promise<boolean>;
    onboardCitizen(citizenPrincipal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitProposal(title: string, description: string, budget: bigint, startTime: Time): Promise<bigint>;
    transfer(to: Principal, amount: bigint): Promise<void>;
    validateWorkLog(workLogId: bigint): Promise<void>;
}
import type { NewWorkLog as _NewWorkLog, UserProfile as _UserProfile, UserRole as _UserRole, ValidationStatus as _ValidationStatus, VotingStatus as _VotingStatus, WorkLog as _WorkLog, WorkLogCategory as _WorkLogCategory, WorkLogTimeSpan as _WorkLogTimeSpan } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkAirdrop(arg0: Array<Principal>, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAirdrop(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAirdrop(arg0, arg1);
            return result;
        }
    }
    async createWorkLog(arg0: NewWorkLog): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkLog(to_candid_NewWorkLog_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkLog(to_candid_NewWorkLog_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllDAOProposals(): Promise<Array<DAOProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDAOProposals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDAOProposals();
            return result;
        }
    }
    async getAllWorkLogs(): Promise<Array<WorkLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkLogs();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkLogs();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCitizenIdByPrincipal(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCitizenIdByPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCitizenIdByPrincipal(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVotingStatus(arg0: bigint): Promise<VotingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getVotingStatus(arg0);
                return from_candid_VotingStatus_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVotingStatus(arg0);
            return from_candid_VotingStatus_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkLogsByCategory(arg0: WorkLogCategory): Promise<Array<WorkLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkLogsByCategory(to_candid_WorkLogCategory_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkLogsByCategory(to_candid_WorkLogCategory_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async onboardCitizen(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.onboardCitizen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.onboardCitizen(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitProposal(arg0: string, arg1: string, arg2: bigint, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProposal(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProposal(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async transfer(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transfer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transfer(arg0, arg1);
            return result;
        }
    }
    async validateWorkLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateWorkLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateWorkLog(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ValidationStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValidationStatus): ValidationStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_VotingStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VotingStatus): VotingStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WorkLogCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkLogCategory): WorkLogCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_WorkLog_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkLog): WorkLog {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ValidationStatus;
    time: _WorkLogTimeSpan;
    description: string;
    category: _WorkLogCategory;
    worker: Principal;
    validations: bigint;
}): {
    id: bigint;
    status: ValidationStatus;
    time: WorkLogTimeSpan;
    description: string;
    category: WorkLogCategory;
    worker: Principal;
    validations: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ValidationStatus_n10(_uploadFile, _downloadFile, value.status),
        time: value.time,
        description: value.description,
        category: from_candid_WorkLogCategory_n12(_uploadFile, _downloadFile, value.category),
        worker: value.worker,
        validations: value.validations
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): ValidationStatus {
    return "pending" in value ? ValidationStatus.pending : "completed" in value ? ValidationStatus.completed : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creative: null;
} | {
    wellness: null;
} | {
    physical: null;
} | {
    knowledge: null;
}): WorkLogCategory {
    return "creative" in value ? WorkLogCategory.creative : "wellness" in value ? WorkLogCategory.wellness : "physical" in value ? WorkLogCategory.physical : "knowledge" in value ? WorkLogCategory.knowledge : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): VotingStatus {
    return "pending" in value ? VotingStatus.pending : "approved" in value ? VotingStatus.approved : "rejected" in value ? VotingStatus.rejected : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkLog>): Array<WorkLog> {
    return value.map((x)=>from_candid_WorkLog_n8(_uploadFile, _downloadFile, x));
}
function to_candid_NewWorkLog_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewWorkLog): _NewWorkLog {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkLogCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkLogCategory): _WorkLogCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    time: WorkLogTimeSpan;
    description: string;
    category: WorkLogCategory;
}): {
    time: _WorkLogTimeSpan;
    description: string;
    category: _WorkLogCategory;
} {
    return {
        time: value.time,
        description: value.description,
        category: to_candid_WorkLogCategory_n5(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkLogCategory): {
    creative: null;
} | {
    wellness: null;
} | {
    physical: null;
} | {
    knowledge: null;
} {
    return value == WorkLogCategory.creative ? {
        creative: null
    } : value == WorkLogCategory.wellness ? {
        wellness: null
    } : value == WorkLogCategory.physical ? {
        physical: null
    } : value == WorkLogCategory.knowledge ? {
        knowledge: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
